namespace :favicon do
  desc "generate a favicon"
  task :generate do
    system <<~SYSTEM
    sketchtool export artboards favicon.sketch > /dev/null
    convert favicon-*.png favicon.ico
    rm favicon-*.png
    SYSTEM
  end
end
